### PR TITLE
第二階段第一週作業 Done

### PR DESCRIPTION
**Pull request by JackTsai890405**
再懇請老師批改

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online testing URLs.

**Comment by JackTsai890405** [comment]
懇請老師幫忙批改 !!!

http://44.199.72.31:3000/api/attraction/100
http://44.199.72.31:3000/api/attractions?page=1 
http://44.199.72.31:3000/api/attractions?page=0&keyword=藝術

**Review by cwpeng — CHANGES_REQUESTED** [review]
Issues below:
1. Response of http://44.199.72.31:3000/api/attractions?page=0 and http://44.199.72.31:3000/api/attractions?page=1 are the same. Page 1 should response 13 ~ 24 attractions, and so on.
2. "images" field of your response should be an array contains every image URL separately, not a string.

Fix issues, create new commits, and ask me to review again.

**Comment by JackTsai890405** [comment]
懇請老師幫忙批改 !!!

http://44.199.72.31:3000/api/attraction/100
http://44.199.72.31:3000/api/attractions?page=1
http://44.199.72.31:3000/api/attractions?page=0&keyword=藝術

**Comment by cwpeng** [comment]
1. Page should be based on 0, not 1, according to API spec.
2. Your images field contains all images of all attractions. Every image field should only contains images of 1 attraction.

After you fixed issues, ask me to review from right side of this page, EXPLICITLY.

**Comment by JackTsai890405** [comment]
懇請老師幫忙批改，這次真ㄉ沒問題ㄌ !!!

http://44.199.72.31:3000/api/attraction/100
http://44.199.72.31:3000/api/attractions?page=1
http://44.199.72.31:3000/api/attractions?page=0&keyword=藝術

**Comment by cwpeng** [comment]
Request me review again from your right side in this page.

**Comment by JackTsai890405** [comment]
懇請老師幫忙批改，這次真ㄉ沒問題ㄌ !!!

http://44.199.72.31:3000/api/attraction/100
http://44.199.72.31:3000/api/attractions?page=1
http://44.199.72.31:3000/api/attractions?page=0&keyword=藝術

**Comment by cwpeng** [comment]
Request me review again from your right side in this page.

**Comment by cwpeng** [comment]
"nextPage" of http://44.199.72.31:3000/api/attractions?page=0&keyword=%E9%A4%A8 should be 1, not 2.

**Comment by JackTsai890405** [comment]
老蘇，這次真ㄉ沒問題ㄌ !!!

http://44.199.72.31:3000/api/attraction/100
http://44.199.72.31:3000/api/attractions?page=1
http://44.199.72.31:3000/api/attractions?page=0&keyword=藝術

**Comment by cwpeng** [comment]
There should have data in page 1 of search result of 館
http://44.199.72.31:3000/api/attractions?page=1&keyword=%E9%A4%A8

You cannot assume there are no more pages than 0 or any other fix number in the searching result.

**Comment by JackTsai890405** [comment]
老蘇，這次真ㄉ沒問題ㄌ !!!

http://44.199.72.31:3000/api/attraction/100
http://44.199.72.31:3000/api/attractions?page=1
http://44.199.72.31:3000/api/attractions?page=0&keyword=藝術

**Review by cwpeng — COMMENTED** [review]
1. We never get all data just for the count of rows, use `SELECT count(*) ...` to get count of rows in query results. I mean you should use count(*) in SQL query below and update related code necessory.
```
"SELECT * FROM `place` WHERE `name` LIKE %s ORDER BY `id`"
```
2. We cannot assume the number of place never change in the lifetime of our website. Your code below is just for fixed number of data, not acceptable.
```
if page == 0:
...
elif page > 0 and page < 4:
...
elif page == 4:
...
else:
```

Fix issues and leave comment for me to review again.

**Comment by JackTsai890405** [comment]
老蘇您好，抱歉繳交如此多次．．．

count(*) and flexible page solution

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggestion: Be professional, you are not a student, not do a homework. You are a professional engineer and do a product which everyone like to use. And then, you can find a better job.

**Pull request merged**
